# Generated by Django 4.2.3 on 2023-07-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_urldata_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='updated_at',
            new_name='last_click_at',
        ),
    ]
